server:
  port: 8888
  servlet:
    context-path: /black
spring:
  application:
    name: my-shiro
  #指定数据库相关信息
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxxxxxx:3306/black_cat_fish?useUnicode=true&characterEncoding=utf-8&autoReconnect=
    username: root
    password: 1qaz@WSX
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: xxxxxxxxx
    port: 6380
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: xxxxxxxxx
    publisher-returns: true
    listener:
      simple:
        retry:
          enabled: true
        default-requeue-rejected: false
      direct:
        retry:
          initial-interval:
          max-attempts: 6
        missing-queues-fatal: true

#  data:
#    mongodb:
#      uri: mongodb://admin:123456@xxxxxxxxx:27017/db1


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.blackfish.shiro.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
